### ISSUE TITLE
Список предустановленных пакетов не отсортирован по алфавиту.

### ISSUE THREAD

**Issue by chiboreache** [yandex-cloud/docs#118]
Неожиданно если честно.

**Comment by chiboreache** [comment]
https://cloud.yandex.ru/docs/datasphere/concepts/preinstalled-packages

**Comment by userdeka** [comment]
Добрый день!
Спасибо большое за замечание и интерес. Переделали [список по алфавиту](https://cloud.yandex.ru/docs/datasphere/concepts/preinstalled-packages#preinstalled-packages) и дополнили сам список заодно.
