### ISSUE TITLE
Добавить информацию как в Windows смонтировать S3 bucket

### ISSUE THREAD

**Issue by shilovk** [yandex-cloud/docs#121]
Хорошо бы сюда [https://cloud.yandex.ru/docs/storage/tools/](https://cloud.yandex.ru/docs/storage/tools/) добавить способ монтирования бакета с помощью [https://github.com/rclone/rclone](https://github.com/rclone/rclone)

Пример инструкции есть здесь [https://github.com/adv4000/s3fs-windows/blob/master/s3rclone-windows.txt](https://github.com/adv4000/s3fs-windows/blob/master/s3rclone-windows.txt)

**Comment by iglunchadze** [comment]
@shilovk, передал команде сервиса про rclone, подумаем.

Если хотите, Вы можете и сами добавить статью в нашу документацию, а мы в рамках [контент-программы](https://cloud.yandex.ru/content-program) дадим вам за это грант :)

**Comment by shoguevara** [comment]
Статья появилась, можно закрыть issue 
https://cloud.yandex.ru/docs/storage/tutorials/s3-disk-connect
