### ISSUE TITLE
Убрать копирование $ при помещении в буфер обмена

### ISSUE THREAD

**Issue by shilovk** [yandex-cloud/docs#122]
В документации везде в начале команд прописан $ и при нажатии значка копирования в буфер, он в итоге туда попадёт и следовательно при вставке каждый раз нужно его удалять. Такого например нет в AWS.
А когда таких операций с десяток, то это каждый раз нужно удалять этот символ.

Решение:
- либо уберите $ в начале команд, что и так понятно
- либо сделайте, чтобы кнопка копирования в буфер была без $

Вот хороший пример, где удобно скопировал в буфер и дальше используешь [https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html)

**Comment by SerjKanunnikov** [comment]
Здравствуйте! Уже планируем работу над таким улучшением. Спасибо за предложение!

**Comment by daeremina** [comment]
Убрали знак `$` из всех команд.
