### ISSUE TITLE
object storage: add guide on SDK for JS/TS

### ISSUE THREAD

**Issue by AlexElin** [yandex-cloud/docs#125]
add guide on SDK for JS/TS for object storage.
Place it under Tools -> SDK

**Comment by iglunchadze** [comment]
Thank you for the suggestion! It took time, but we've just published our own article about getting AWS SDK for JavaScript to work with Object Storage. Here it is in Russian:

https://cloud.yandex.ru/docs/storage/tools/aws-sdk-js

English version will follow soon.
