### ISSUE TITLE
terraform-quickstart(rus): an example doesn't contain `terraform` section

### ISSUE THREAD

**Issue by AlexElin** [yandex-cloud/docs#134]
The [english guide](https://cloud.yandex.com/en/docs/solutions/infrastructure-management/terraform-quickstart) containst `terraform` section with `required_providers` definition.  
But the [russian version](https://cloud.yandex.ru/docs/solutions/infrastructure-management/terraform-quickstart) - not.
This results in error when running the russian version's example on terraform 0.14+

**Comment by a-chegodaev** [comment]
Hello! We are already working on this improvement. Thank you for your suggestion!

**Comment by a-chegodaev** [comment]
We fixed [the example](https://cloud.yandex.ru/docs/solutions/infrastructure-management/terraform-quickstart).
