### ISSUE TITLE
Нерабочая документация в примере с Kubernetes + GitLab для непрерывного развертывания контейнезированных приложений

### ISSUE THREAD

**Issue by ssitdikov** [yandex-cloud/docs#165]
https://cloud.yandex.ru/docs/solutions/infrastructure-management/gitlab-containers#ci

Пример нерабочий, образ `gcr.io/cloud-builders/kubectl:latest` не дает возможности работать с Кубером на Яндексе, запрашивает дополнительные env, а потом валится с тем, что нет таких.

В примере по сборке - `dind` тоже из коробки не запускается, на `StackOverflow` есть подсказки (где какую версию образа указать).

Спасибо.

**Comment by SerjKanunnikov** [comment]
Спасибо! Возьмем в работу и поправим.

**Comment by mashkovd** [comment]
я давно заменил **gcr.io/cloud-builders/kubectl:latest** на **lwolf/helm-kubectl-docker:latest**, в котором присутствует kubectl+helm. В примерах от YC не хватало прмиера развертывания средствами helm.

**Comment by daeremina** [comment]
Простите за долгое ожидание! Мы поправили документацию: https://cloud.yandex.ru/docs/solutions/infrastructure-management/gitlab-containers
Спасибо, что делаете документацию Yandex Cloud лучше!

**Comment by premiumitsolution** [comment]
Проблема так и осталась не решенной, документация обрывается на пол пути после "Добавьте две переменные окружения:
KUBE_URL – адрес [мастера Yandex Managed Service for Kubernetes](https://cloud.yandex.ru/docs/managed-kubernetes/concepts/#master). Узнайте его с помощью команды:" ;(
