### ISSUE TITLE
Несоответствие документации по обеспечению доступности приложения в kubernetes со статусом готовности внутреннего балансировщика

### ISSUE THREAD

**Issue by n0nvme** [yandex-cloud/docs#186]
В описании создания сервиса для managed service for kubernetes с внутренним load balancer нет ни слова о том что внутренний сетевой балансировщик нагрузки находится в стадии preview

https://cloud.yandex.ru/docs/managed-kubernetes/operations/create-load-balancer#lb-int-create

https://cloud.yandex.ru/docs/network-load-balancer/concepts/internal-load-balancer

![image](https://user-images.githubusercontent.com/20794752/131820529-bfed2540-f4bf-40a6-8b7d-4453605b98bf.png)

![image](https://user-images.githubusercontent.com/20794752/131820587-84edce10-edf0-48cb-99c3-a052e2e4e305.png)

**Comment by iglunchadze** [comment]
@n0nvme, спасибо, что обратили внимание! Скоро добавим уточнение про стадию Preview в документацию Managed Service for Kubernetes. Извините, что так долго не могли добраться.

**Comment by iglunchadze** [comment]
Добавили плашку в инструкцию: https://cloud.yandex.ru/docs/managed-kubernetes/operations/create-load-balancer#lb-int-create
