### ISSUE TITLE
Активированную роль Remote Desktop Licensing Server

### ISSUE THREAD

**Issue by patsevanton** [yandex-cloud/docs#191]
https://cloud.yandex.ru/docs/microsoft/list-of-instances#changes

Все доступные в Cloud Marketplace образы включают в себя установленный Windows Server 2019 Datacenter с предварительно активированной ролью Remote Desktop Licensing Server и пакетом пользовательских лицензий. 

А я не вижу предварительно активированную роль Remote Desktop Licensing Server

![3](https://user-images.githubusercontent.com/10828883/133898361-e9a7d023-70eb-472f-90ca-046d7628e69a.png)

**Comment by ekodian** [comment]
это ошибка в доке, только в rds образах такое

**Comment by patsevanton** [comment]
@ekodian А где найти RDS образы?

**Comment by ekodian** [comment]
https://cloud.yandex.ru/marketplace?search=RDS

**Comment by patsevanton** [comment]
Тогда правильно было бы переписать этот тест так:
```
Все доступные в Cloud Marketplace образы, в названии которых есть [RDS](https://cloud.yandex.ru/marketplace?search=RDS), включают в себя активированную роль Remote Desktop Licensing Server и пакет пользовательских лицензий.
```
