### ISSUE TITLE
Опечатка в документации "Интеграция с Yandex Object Storage"

### ISSUE THREAD

**Issue by Wolfeg** [yandex-cloud/docs#196]
В 8 пункте ["Создание ресурсов csi"](https://cloud.yandex.ru/docs/managed-kubernetes/operations/volumes/s3-csi-integration) продублирован attacher.yaml
```
kubectl create -f secret.yaml && \
kubectl create -f k8s-csi-s3/deploy/kubernetes/provisioner.yaml && \
kubectl create -f k8s-csi-s3/deploy/kubernetes/attacher.yaml/attacher.yaml && \
kubectl create -f k8s-csi-s3/deploy/kubernetes/csi-s3.yaml && \
kubectl create -f storageclass.yaml
```

**Comment by maxdunaevsky-documentatio** [comment]
@SerjKanunnikov , привет! Кажется, уже не актуально. Вот что сейчас в текущей версии документации:

```bash
kubectl create -f secret.yaml && \
kubectl create -f k8s-csi-s3/deploy/kubernetes/provisioner.yaml && \
kubectl create -f k8s-csi-s3/deploy/kubernetes/attacher.yaml && \
kubectl create -f k8s-csi-s3/deploy/kubernetes/csi-s3.yaml && \
kubectl create -f storageclass.yaml
```

**Comment by daeremina** [comment]
Здравствуйте, спасибо за информацию!

Действительно, в процессе улучшения документации эта ошибка уже исправлена: https://cloud.yandex.ru/docs/managed-kubernetes/operations/volumes/s3-csi-integration#configure-csi

**Comment by h8nor** [comment]
> будет не будет
https://github.com/yandex-cloud/docs/blob/c6d83d09df43a3ea0c59156d704335485105415c/guides/yfm-syntax-ru.md#L385
