### ISSUE TITLE
Некорректный текст ссылки на тарифы в документации Cloud CDN

### ISSUE THREAD

**Issue by kaero** [yandex-cloud/docs#197]
https://cloud.yandex.ru/docs/cdn/concepts/origins-shielding

![Screenshot 2021-09-26 at 13-05-41 Документация Yandex Cloud Yandex Cloud CDN Экранирование источников](https://user-images.githubusercontent.com/352609/134803511-0d9d6ea9-b42e-498e-83e5-48c8113d07b9.png)

В исходнике ссылка выглядит аналогично соседним страницам, где текст ссылки отрендерен корректно. Не увидел разницы в разметке, чтобы предложить исправление.

**Comment by iglunchadze** [comment]
Филипп, здравствуйте! Мы тоже иногда такое наблюдаем, но, по опыту, помогает обновление страницы. О проблеме с вёрсткой мы знаем, будем чинить.
