### ISSUE TITLE
Разное описание доступных платформ на русском и английском языках

### ISSUE THREAD

**Issue by zuzzas** [yandex-cloud/docs#199]
На [русском](https://github.com/yandex-cloud/docs/blob/master/ru/compute/concepts/vm-platforms.md) доступно больше платформ, чем на [английском](https://github.com/yandex-cloud/docs/blob/master/en/compute/concepts/vm-platforms.md).

**Comment by SerjKanunnikov** [comment]
Уже работаем над обновлением, спасибо!

**Comment by daeremina** [comment]
Количество платформ на [русском](https://github.com/yandex-cloud/docs/blob/master/ru/compute/concepts/vm-platforms.md) и [английском](https://github.com/yandex-cloud/docs/blob/master/en/compute/concepts/vm-platforms.md) языках сейчас одинаково.
