### ISSUE TITLE
В справочнике YQL отстуствует функция AGGREGATE_LIST

### ISSUE THREAD

**Issue by gayratv** [yandex-cloud/docs#208]
https://github.com/yandex-cloud/docs/blob/master/ru/ydb/yql/reference/overview.md
https://cloud.yandex.ru/docs/ydb/yql/reference/overview

В справочнике YQL функция AGGREGATE_LIST отсутствует :)
Поиск показывает что она встречается только один раз в примере выборки.

Какие есть еще "скрытые" полезные функции ?
Есть ли какое то секретное место где они перечислены ?

Просьба добавить хотя бы AGGREGATE_LIST в документацию в раздел справочник.

**Comment by bazeltsev** [comment]
Здравствуйте!
Описание функции AGGREGATE_LIST будет добавлено в ближайшее время.
Спасибо, что помогаете нам стать лучше!
