### ISSUE TITLE
Добавить пояснение о не возможности вкл./откл. DDoS Protection к уже арендованному ip

### ISSUE THREAD

**Issue by shilovk** [yandex-cloud/docs#211]
[https://github.com/yandex-cloud/docs/blob/master/ru/vpc/operations/enable-ddos-protection.md](https://github.com/yandex-cloud/docs/blob/master/ru/vpc/operations/enable-ddos-protection.md)

Нужно явно написать, чтобы не гадать:
"Включить или выключить опцию DDoS Protection на уже выданном адресе не получится технически, так как адреса с DDoS защитой и без неё выдаются из разных пулов." - выдержка из общения с техподдержкой.

**Comment by SerjKanunnikov** [comment]
Здравствуйте! Взяли в работу, скоро обновим документацию

**Comment by SerjKanunnikov** [comment]
Обновили страничку: https://cloud.yandex.ru/docs/vpc/operations/enable-ddos-protection
Спасибо!
