### ISSUE TITLE
описание AWS SDK C++   для object storage  

### ISSUE THREAD

**Issue by alehay** [yandex-cloud/docs#216]
хотелось бы добавить в документацию на равне с  java , python и С# вот в этом разделе
https://cloud.yandex.ru/docs/storage/tools/aws-sdk-java 
инструкцию для AWS SDK C++.

**Comment by iglunchadze** [comment]
@alehay, мы рады, что Вы хотите сделать нашу документацию лучше! Чтобы начать вместе с Вами работу над описанием SDK, пожалуйста, создайте пул-реквест с черновиком — файлом в формате Yandex Flavored Markdown (YFM) в папке ru/storage/tools. Подробности есть в [инструкции](https://github.com/yandex-cloud/docs/blob/master/guides/how-to-contribute.md) по работе с репозиторием, руководствах по [стилю](https://github.com/yandex-cloud/docs/blob/master/guides/how-to-write.md) и [синтаксису YFM](https://ydocs.tech/ru/) и [соглашении с контрибьютором](https://github.com/yandex-cloud/docs/blob/master/CONTRIBUTING.md).

**Comment by SerjKanunnikov** [comment]
Забрали PR #223
