### ISSUE TITLE
Некорректная картинка в статье об управлении доступом в CDN

### ISSUE THREAD

**Issue by luixo** [yandex-cloud/docs#230]
https://github.com/yandex-cloud/docs/blob/master/ru/dns/security/index.md#какие-роли-действуют-в-сервисе-roles-list
Похоже, картинка из load testing'а

**Comment by SerjKanunnikov** [comment]
Поправим, спасибо!

**Comment by SerjKanunnikov** [comment]
Убрали Load Testing, спасибо.
