### ISSUE TITLE
"Site visit statistics by browser": describe how to add this info into Yandex Datalens

### ISSUE THREAD

**Issue by AlexElin** [yandex-cloud/docs#236]
Service: Object Storage. Documentation.

I'd like to have a some chart/dashboard in Yandex Monitoring showing site visit statistics by browser.
Currently the [docs](https://cloud.yandex.com/en/docs/storage/solutions/user-agent-statistics) descibe only how to dsiplay this info in a command line.

I think it'd be helpful to add instruction how to display this information in Yandex Datalens

**Comment by iglunchadze** [comment]
Hi Alex! This use case is described by our developers in their blog posts on Medium (in Russian):

* https://nikolaymatrosov.medium.com/анализ-логов-object-storage-при-помощи-datalens-9c0c0d99c3a0
* https://kbespalov.medium.com/яндекс-облако-визуализация-данных-биллинга-в-сервисе-datalens-98ca3ae9d5a1

Note that both solutions involve writing logs to an intermediary database, e.g. ClickHouse, as currently neither Monitoring nor DataLens supports direct connections to Object Storage buckets.

We'll consider adding similar instructions to the official documentation. Thank you for the suggestion!

**Comment by AlexElin** [comment]
Yeah, it would be helpful to have this information in the official docs

**Comment by AlexElin** [comment]
just in case, is it possible to use Yandex Database in a serverless mode instead of ClickHouse?
If yes, will it be cheaper?

**Comment by SerjKanunnikov** [comment]
It depends on your use case. You can ask for details in the Yandex Database Telegram chat: https://t.me/yandexdatabase_ru 
Our developers and support are there to help you :)
