### ISSUE TITLE
Datepicker allows enetering wrong value while a creating a budget

### ISSUE THREAD

**Issue by AlexElin** [yandex-cloud/docs#237]
Datepicker allows enetering a wrong value while a creating a budget.
Only after pressing a submit button, a user will know that the value is wrong.

I'd suggest excluding wrong dates from the datepicker.

Steps to reproduce the current bevahior.
1. Open Billing -> Choose a payment account ->Budgets -> Create a budget
2. Fill the form as on the below screenshot. Setting the date to the one from 2050 year.
3. Press Submit button

Actual behvaior: the error message is shown stating that the date invalid
 
![image](https://user-images.githubusercontent.com/13061803/142008432-7b19f7d3-9589-4d44-92ad-cc78bc7800e6.png)

**Comment by tatlush** [comment]
Hello! 
This is documentation repo. 
As you can see, this limitation for Expires date is described in [docs](https://cloud.yandex.ru/docs/billing/operations/budgets). If you think the improvement can be useful, please write to Support or leave the suggestion at the [Community](https://cloud.yandex.ru/features) page.
