### ISSUE TITLE
Написал документацию и код для подключения (без ограничений во времени) к YandexSpeechKit

### ISSUE THREAD

**Issue by eighteight** [yandex-cloud/docs#240]
https://github.com/eighteight/YandexSpeechKitMicrophoneSTT

Аккаунт vladimir@scriptum.ru

**Comment by tatlush** [comment]
Добрый день! 
Мы внимательно изучили ваше решение, и, к сожалению, пока не готовы рекомендовать его пользователям.
Спасибо за проявленный интерес к документации Yandex.Cloud! Ждем ваших новых идей.
