### ISSUE TITLE
ETag description

### ISSUE THREAD

**Issue by RCheese** [yandex-cloud/docs#25]
Is it completely Amazon ETag or is there any difference?

[This description is very short](https://github.com/yandex-cloud/docs/blob/master/ru/storage/s3/api-ref/common-response-headers.md)

**Comment by zamulla** [comment]
Hi, @RCheese! Sorry for the delay.

Yes, Yandex Object Storage uses ETag in exactly the same way as Amazon. The description will be expanded to reflect that, thanks for pointing it out.
