### ISSUE TITLE
Начало работы с Терраформ, ошибка с инструкцией

### ISSUE THREAD

**Issue by dshubenok** [yandex-cloud/docs#253]
Не стал править сам, но есть проблема. Если идти строго по инструкции, то ругается на строку
yandex_vpc_network.network-1.id
в листинге для Терраформ (https://cloud.yandex.ru/docs/solutions/infrastructure-management/terraform-quickstart)

Возможно, стоит взять это в "<>", чтобы было понятно, что нужно вставить айди существующей сети.

**Comment by daeremina** [comment]
Изменили на `network_id = yandex_vpc_network.default.id`, предварительно задав сеть `default`: https://cloud.yandex.ru/docs/tutorials/infrastructure-management/terraform-quickstart#prepare-plan
