### ISSUE TITLE
В документации по IAM описана работа с Organization

### ISSUE THREAD

**Issue by rgeraskin** [yandex-cloud/docs#254]
В документации по IAM многие действия предлагается сделать с помощью сервиса Organization. Однако добавить пользователя в облако можно, например, и без Organization. Является ли использование Organization для IAM новым best practice, или здесь просто какая-то ошибка?

Практически одно и то же:
- https://cloud.yandex.ru/docs/iam/operations/users/create
- https://cloud.yandex.ru/docs/organization/add-account

**Comment by tatlush** [comment]
Здравствуйте, Роман!
Yandex Cloud Organization — это решение для корпоративных клиентов. Не всем пользователям нужен этот сервис, поэтому выбор всегда остается за вами. 
В дублировании инструкций нет никакой ошибки. 
Спасибо, что проявляете интерес к документации Yandex.Cloud!

**Comment by rgeraskin** [comment]
Кажется, вы сами себе противоречите. Если не всем пользователем нужен этот сервис - то зачем для добавления пользователя предлагается в первую очередь использовать Yandex Cloud Organization?
