### ISSUE TITLE
Использование ES модулей в облачных функциях на Node.js

### ISSUE THREAD

**Issue by vitalets** [yandex-cloud/docs#270]
Здравствуйте!

Хочу написать небольшую инструкцию о том, как использовать es модули в облачных функциях на Node.js.
Это актуально, т.к. многие пакеты [переходят](https://github.com/sindresorhus/meta/discussions/15) на формат esm-only. 
А функции всегда запускаются как commonjs, и нужна некоторая настройка.
Что скажете?
И если подходит, то в каком разделе это лучше разместить?

**Comment by myusosnovskay** [comment]
Здравствуйте!

Будем рады, если вы принесете нам такую инструкцию. Положить ее можно в раздел Разработка на Node.js.
