### ISSUE TITLE
windows: невозможно создать папку aux

### ISSUE THREAD

**Issue by gayratv** [yandex-cloud/docs#273]
В последнем релизе в репозитарии создана папка с именем aux

В разработке я использую windows 10, а в windows 10 создать папку aux невозможно (запрещено системой).

Попытка сделать git pull выдала:
fatal: cannot create directory at 'ru/ydb/reference/ydb-sdk/example/_includes/aux': Invalid argument

Переименуйте пожалуйста папку aux

**Comment by myusosnovskay** [comment]
Поправили.
