### ISSUE TITLE
Формат не отображается в английской версии документации

### ISSUE THREAD

**Issue by Fxlr8** [yandex-cloud/docs#284]
https://github.com/yandex-cloud/docs/blob/90554532e75d954f05d608117644dfe5880b7d00/en/functions/quickstart/create-function/node-function-quickstart.md?plain=1#L117

<img width="792" alt="image" src="https://user-images.githubusercontent.com/10725007/151350106-8205b9b1-3a74-47fc-accb-39579bc10f20.png">

**Comment by myusosnovskay** [comment]
Спасибо, что обратили внимание! Поправили.
