### ISSUE TITLE
Не рабочая документация на примере работы с Helm Chart

### ISSUE THREAD

**Issue by MikeVL** [yandex-cloud/docs#286]
При попытке загрузить файл в репозиторий выдаёт ошиьбки

```
helm push app-0.1.0.tgz oci://cr.yandex/cr.yandex/***/app:0.1.0`
Error: invalid_reference: invalid tag
```
```
helm push app-0.1.0.tgz oci://cr.yandex/cr.yandex/***/app`
Error: unexpected status: 404 Not Found
```
```
helm push cr.yandex/cr.yandex/***/app:0.1.0
Error: "helm push" requires at least 2 arguments
```

```
helm version
version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}
```

**Comment by sigurdblueface** [comment]
https://cloud.yandex.ru/docs/application-load-balancer/tools/k8s-ingress-controller/#install
```╰─ helm pull \
  --version v0.1.9 \
  oci://cr.yandex/yc/yc-alb-ingress-controller-chart

Error: cr.yandex/yc/yc-alb-ingress-controller-chart:v0.1.9: not found
```

**Comment by iglunchadze** [comment]
Здравствуйте! Простите, что так долго добирались до этой задачи.

@MikeVL, вижу в ваших командах несколько потенциальных проблем. 

* В URI, на который вы хотите отправить чарт, по два раза повторяется доменное имя `cr.yandex`. В правильной команде оно должно быть один раз, и сразу после него — идентификатор вашего реестра в Container Registry.
* Также в URI не нужно указывать полный путь к чарту — только к реестру.
* Команда не должна заканчиваться бэктиком `` ` ``.

То есть правильная команда, как и сказано в [документации](https://cloud.yandex.ru/docs/container-registry/operations/helm-chart/helm-chart-push), в вашем случае будет выглядеть так:

```bash
helm push app-0.1.0.tgz oci://cr.yandex/***
```

Если будете сталкиваться с подобными проблемами в будущем, обращайтесь в [службу технической поддержки](https://cloud.yandex.ru/docs/support/overview).

**Comment by iglunchadze** [comment]
@sigurdblueface, в документации сейчас действительно указан неверный URI Helm-чарта Ingress-контроллера. Правильная команда такая:

```bash
helm pull oci://cr.yandex/yc-marketplace/yandex-cloud/yc-alb-ingress/yc-alb-ingress-controller-chart --version v0.1.13
```

Актуальная команда всегда есть на [карточке контроллера как продукта Marketplace](https://cloud.yandex.ru/marketplace/products/yc/alb-ingress-controller#docker-images), в разделе «Состав продукта». Но и документацию мы тоже уже правим и, как только это сделаем, отпишемся здесб. Спасибо, что обратили внимание!

**Comment by akamac** [comment]
документацию так и не поправили
