### ISSUE TITLE
DataSphere. Пример Docker-образа на основе оригинального образа tensorflow.

### ISSUE THREAD

**Issue by DanilZittser** [yandex-cloud/docs#297]
Добрый день!

Предлагаю добавить пример Docker-образа на основе оригинального образа `tensorflow`. В текущей документации пример есть, но он довольно тяжёлый для восприятия. Пример ниже прост, понятен:

```dockerfile
FROM tensorflow/tensorflow:2.7.0-gpu

RUN set -e \
  && useradd -ms /bin/bash --uid 1000 jupyter \
  && pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir nptyping==1.4.4 pandas==1.4.1 opencv-python-headless==4.5.5.62 scikit-learn==1.0.2 \
  && ln -s /usr/bin/python3 /usr/local/bin/python3
```

[Ссылка](https://cloud.yandex.ru/docs/datasphere/operations/user-images#create) на страницу документации, куда его стоит поместить.

**Comment by tatlush** [comment]
@DanilZittser, сегодня мы включили его в документацию Yandex DataSphere.
Пожалуйста, сообщите свой идентификатор платежного аккаунта, мы начислим на него грант. Спасибо, что помогаете делать документацию лучше!
