### ISSUE TITLE
Добавить практические инструкции для Pulumi

### ISSUE THREAD

**Issue by imajus** [yandex-cloud/docs#302]
Я активно использую [Pulumi](https://www.pulumi.com/) вместо Terraform и предлагаю добавить в документацию YC практические примеры использования, которые затрагивают настройку различных сервисов YC:

1. Cloud Compute:
    1. Базовые примеры
    2. Нюансы работы с COI
    3. Интеграция с Cloud Logging
4. IAM
5. Serverless Containers
6. Cloud DNS
7. Load Balancer
8. Container Registry

Список будет расширяться по мере того, как мне потребуется настроить другие компоненты в YC.

**Comment by imajus** [comment]
Хочу написать сам. Согласно инструкции к этому репозиторию создал Issue.

**Comment by daeremina** [comment]
@imajus , простите за долгое ожидание. Если вы всё ещё хотите написать инструкции, мы с радостью примем их в документацию и выдадим вам грант в рамках [контент-программы](https://cloud.yandex.ru/content-program).

Будем ждать ваших пул-реквестов!
