### ISSUE TITLE
[ru/iam/concepts/users/service-accounts.md] Не описаны правила именования сервис аккаунтов

### ISSUE THREAD

**Issue by boryasabidaev** [yandex-cloud/docs#303]
Отсутствует информация о том, что имена сервис аккаунтов должны быть уникальны в рамках облака.
Интуитивно складывается представление, что имена сервис аккаунтов должны быть уникальны в рамках каталога, так как создаются в определенном каталоге.

**Comment by nikolaymatrosov** [comment]
Fixed in https://github.com/yandex-cloud/docs/commit/596485aa3f965977447b6362154b78b07ff52ed8#diff-528cd0b87781ca67b0810cebbe57b89a04cd4cff1230f53d1e95866f0a0f0d41
