### ISSUE TITLE
Корректировки в документации по OpenVPN

### ISSUE THREAD

**Issue by YHx07** [yandex-cloud/docs#306]
При создании виртульной машины создается пользователь с именем `openvpn_as`.

Выполенение команды
```
$ sudo passwd openvpn
```
Выдает `passwd: user 'openvpn' does not exist`

**Comment by avzin172** [comment]
Спасибо! Если проблема еще актуальна, посмотрите [здесь](https://cloud.yandex.ru/docs/tutorials/routing/openvpn#create-openvpn-instance).

**Comment by YHx07** [comment]
Спасибо, проблема решена!
