### ISSUE TITLE
Не рабочая документация подключения к YDB для ноды

### ISSUE THREAD

**Issue by higimo** [yandex-cloud/docs#321]
Тут даже близко к чему-то работающему просто нет. В «Создайте функцию» какой-то файл надо редактировать. Даже если я догадаюсь как его создать и чем заполнить, самое главное происходит в файлах first-setup-func.sh deploy.sh — и именно про них вообще ничего не написано. Всякой пены про тарифы указано в десятый раз, а пользы — ноль.

Ещё тестирование из 6 пунктов. А что тестировать, почему оно так работает?

Вероятно, соседняя ишу поможет https://github.com/yandex-cloud/docs/issues/280

**Comment by myusosnovskay** [comment]
Здравствуйте!

Вы про [эту инструкцию](https://cloud.yandex.ru/docs/functions/tutorials/connect-to-ydb-nodejs)? Файл main.env вы можете найти по [ссылке](https://github.com/yandex-cloud/examples/tree/master/serverless/functions/YDB-connect-from-serverless-function). Ссылка указана в разделе Подготовьте окружение.

**Comment by gayratv** [comment]
К сожалению от моего текста, который я писал мало что осталось :)

Но вот тут:
https://github.com/yandex-cloud/examples/tree/master/serverless/functions/YDB-connect-from-serverless-function

лежит пример с большим readme в котором я подробно все описал :)

Ссылка на репозитарий приведена в документации под пунктом 1
Клонируйте [репозиторий examples](https://github.com/yandex-cloud/examples/tree/master/serverless/functions/YDB-connect-from-serverless-function) с помощью Git.

Прошло уже конечно много времени с момента Вашего вопроса, но я не из Яндекса

**Comment by daeremina** [comment]
Сейчас [документация по подключению к БД Yandex Managed Service for YDB из функции Cloud Functions на Node.js](https://cloud.yandex.ru/docs/functions/tutorials/connect-to-ydb-nodejs) актуальная, сценарий использования рабочий.

**Comment by guideblade** [comment]
А кто-нибудь знает как подключить эту штуку к node.js? Без облачных функций, просто у меня папка на компе с проектом node.js и .ts файлами, запускаю я это все с помощью npm run start.
Единственное, что нашел это эту инструкцию: https://ydb.tech/en/docs/reference/ydb-sdk/example/example-nodejs. И тут ничего не понятно. Есть блок кода и куда его писать? Я установил ydb-sdk. Я пишу этот блок кода в app.ts и конечно он не распознает getCredentialsFromEnv()! Откуда эта функция вообще должна взяться? И что значит Env? Я делал проект без виртуалки. Почему нигде не написано как просто подключить эту штуку и начать делать SQL запросы?
