### ISSUE TITLE
Создание репозитория с документацией на gitflic

### ISSUE THREAD

**Issue by jsmarketingrus** [yandex-cloud/docs#331]
Предлагаю создать на gitflic.ru клон данного репозитория. Сейчас по запросу Яндекс на сервисе найден 1 репозиторий) Несерьезно. Готов выполнить эту задачу и контролировать актуальность, если компания доверит действовать от ее имени.

**Comment by tatlush** [comment]
Добрый день! Мы не планируем использовать  gitflic.ru и другие площадки.
