### ISSUE TITLE
добавьте возможность создания перманентного токена что бы API дергать спокойно

### ISSUE THREAD

**Issue by AlexanderKozhevin** [yandex-cloud/docs#337]

**Comment by tatlush** [comment]
@AlexanderKozhevin, добрый день! 
Использование метода авторизации с неограниченным сроком действия доступно для некоторых сервисов Yandex Cloud. Подробнее об авторизации с помощью API-ключа можно почитать [в документации](https://cloud.yandex.ru/docs/iam/concepts/authorization/api-key). Однако мы считаем этот метод авторизации менее безопасным.
Если у вас есть предложения, как улучшить Yandex Cloud, пожалуйста, оставьте его в нашем [сообществе](https://cloud.yandex.ru/features).
