### ISSUE TITLE
YDB YQL неверная документация

### ISSUE THREAD

**Issue by gayratv** [yandex-cloud/docs#342]
Вот тут

https://github.com/yandex-cloud/docs/blob/master/en/ydb/yql/reference/builtins/_includes/basic/random.md

упоминается функция 
RandomUuid

**Ошибка:**

Вызов RandomUuid() приводит к ошибке

**Правильно:**

RandomUuid('Uuid version 4')

Добавьте пожалуйста в документацию описание параметров функции RandomUuid, какие еще возможны значения кроме 'Uuid version 4' ?

**Comment by bazeltsev** [comment]
Здравствуйте, @gayratv.
RandomUuid не может быть без параметров. В описании сигнатур именно так: RandomUuid(T1[, T2, ...])->Uuid.
