### ISSUE TITLE
Название не отображает суть.

### ISSUE THREAD

**Issue by martelev** [yandex-cloud/docs#37]
Как я понял, "распознавание длинных аудио" не отображает суть API. Насколько я понял, это API рассчитано не на длину аудиофайлов, а на те задачи, которые не требуют быстрого ответа на запрос.

**Comment by Wedmal** [comment]
Список неработающих ссылок:
https://github.com/yandex-cloud/docs/blob/master/ru/speechkit/stt/streaming.md#specification-msg
https://github.com/yandex-cloud/docs/blob/master/ru/speechkit/stt/streaming.md#audio-msg
https://github.com/yandex-cloud/docs/blob/master/ru/speechkit/stt/streaming.md#response
https://github.com/yandex-cloud/docs/blob/master/ru/speechkit/stt/streaming.md#examples
https://github.com/yandex-cloud/docs/blob/master/ru/speechkit/stt/streaming.md#specification-msg

**Comment by tatlush** [comment]
Здравствуйте!
После столь долгой задержки рады, наконец, сообщить, что мы реорганизовали раздел с информацией о распознаваниях и изменили их названия.
Еще раз спасибо за ваш интерес к документации Yandex.Cloud.
