### ISSUE TITLE
Криво описана тарификация smartcaptcha

### ISSUE THREAD

**Issue by Leonid-SLV** [yandex-cloud/docs#373]
Строку:
Например, стоимость 250 001 запроса составит 0,1 ₽, при условии стоимости 1 тысячи запросов 100 ₽.

Поменяйте на:
Например, стоимость первых 250 001 запроса в месяц составит 0.1₽. В дальнейшем 1₽ за каждые 250 запросов на валидацию, согласно действующей тарификации.

Идентификатор аккаунта b1gbjkqc5t27ppf3seh6

**Comment by kamkib** [comment]
Добрый день. Пример исправлен:
https://cloud.yandex.ru/docs/smartcaptcha/pricing
