### ISSUE TITLE
Broken example of using SpeechKit API v3

### ISSUE THREAD

**Issue by gusev-genotek** [yandex-cloud/docs#380]
After running https://cloud.yandex.ru/docs/speechkit/stt/api/streaming-examples-v3 I get an error
```
Error code StatusCode.UNAUTHENTICATED, message: You have to specify folder ID for user account
```
Folder ID is nowhere mentioned in this example

**Comment by tatlush** [comment]
Добрый день, @gusev-genotek!
Этот пример выполняется с использованием сервисного аккаунта — для него folder ID действительно не нужен, потому что СА живет в пределах своего каталога и берет его идентификатор. Если выполнять пример "человеческим" аккаунтом — Яндекс ID или федеративный аккаунт, то для любого действия с любым API Yandex SpeechKit нужен folder ID. Подробнее о методах аутентификации в API написано здесь: https://cloud.yandex.ru/docs/speechkit/concepts/auth

Пожалуйста, попробуйте выполнить пример от имени сервисного аккаунта, и если не получится, то дайте нам знать.
