### ISSUE TITLE
Пошаговая инструкция для развертывания Wazuh как DevSecOps платформы

### ISSUE THREAD

**Issue by pyToshka** [yandex-cloud/docs#382]
Инструкция как развернуть  Wazuh Open Source платформу в Яндекс Cloud

### Что такое Wazuh
Wazuh это HIDS с открытом исходным кодом, изначально это форк OSSEC, команда разработчиков Wazuh отделилась от разработки OSSEC в 2015(примерно) из-за разногласий в разработки и из-за медленного развития OSSEC
### Wazuh архитектура
![wazuh](https://documentation.wazuh.com/current/_images/deployment1.png)

### Wazuh use cases

- Log data analysis
- File integrity monitoring
- Rootkits detection
- Active response
- Configuration assessment
- System inventory
- Vulnerability detection
- Cloud security
- Container security
- Regulatory compliance

### Что будет в how to
- Подготовка образа виртуальной машины
- Автоматизация развертывания
- Создание all-in-one в Yandex cloud
- Базовая конфигурация Wazuh
- Подключение агентов

### Tools
- Wazuh  v4.3.5
- terraform 
- packer

Официальный сайт https://wazuh.com/

**Comment by daeremina** [comment]
Простите за долгое ожидание. Сейчас в Yandex Cloud Marketplace есть продукт [Wazuh](https://cloud.yandex.ru/marketplace/products/opennix/wazuh) и инструкция по его разворачиванию на платформе.
