### ISSUE TITLE
Не рабочая ссылка на странице

### ISSUE THREAD

**Issue by ShaDream** [yandex-cloud/docs#386]
Не работает ссылка в  [данном](https://cloud.yandex.ru/docs/functions/security/#about-access-control) пункте, а именно [Yandex Identity and Access Management](https://cloud.yandex.ru/docs/_includes/iam)

**Comment by tatlush** [comment]
Большое спасибо, что обратили на это внимание! Мы поправили, теперь ссылка работает.
