### ISSUE TITLE
Bulder delete toc.yaml

### ISSUE THREAD

**Issue by i-terezie** [yandex-cloud/docs#392]
I'm trying to compile documentation from multiple locations into one resulting directory. To do this, I wrote the following toс.yam

```
title: Имя документа
href: index.yaml
items:
  - include: {mode: merge, path: /home/iliya/Projects/Cmos1300Ch16/doc/toc.yaml }
```
 
 
As a result, the /home/iliya/Projects/Cmos1300Ch16/doc/toc.yaml file is deleted. Although the result is similar to what I expect. I note that modifying the source directory is a bad idea.

**Comment by daeremina** [comment]
@yndx-birman can you help with this issue?

**Comment by yndx-birman** [comment]
@i-terezie absolute paths are not supported in toc.yaml, instead use relative paths
when starting builder copies all source doc files to a temporary directory and works with them
