### ISSUE TITLE
Добавление зависимости НЕ из npm репозитория в Node.js serverless функциях

### ISSUE THREAD

**Issue by itPiligrim** [yandex-cloud/docs#398]
Создается проект, в котором часть зависимостей в package.json берется из закрытого репозитория.
Как правильно их добавить в serverless функцию?
Опытным путем было установлено, что если в архив с исходным кодом serverless функции добавить node_modules с этими пакетами, то все работает. Но это не задокументировано. Верный ли это способ и если да, то было бы полезно дополнить документацию.

**Comment by nikolaymatrosov** [comment]
Да, это верное решение. Вообще-то про это сказано [тут](https://cloud.yandex.ru/docs/functions/concepts/function#upload):
```
Для создания версии вы можете ... загрузить код и необходимые зависимости...
```
