### ISSUE TITLE
Не корректный пример speechkit tts v3

### ISSUE THREAD

**Issue by xvost** [yandex-cloud/docs#404]
В документации описывающей взаимодействие с сервисом через grpc api не хватает указания folder-id, так как используется авторизация через iam токен и как указано в документации iam, при его использовании требуется указание каталога.
Также, хорошо бы было добавить в пример указание голоса озвучивания.

Добавляем указание каталога
```   # Отправить данные для синтеза.
    it = stub.UtteranceSynthesis(request, metadata=(
        ('authorization', f'Bearer {iam_token}'),
        ('x-folder-id', f'{folderid}')
...

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--token', required=True, help='IAM token')
    parser.add_argument('--text', required=True, help='Text for synthesis')
    parser.add_argument('--output', required=True, help='Output file')
    parser.add_argument('--folderid', required=True, help='Folder ID')
    args = parser.parse_args()

    ))
```

Добавляем указание голоса
```
def synthesize(iam_token, text, folderid) -> pydub.AudioSegment:
    request = tts_pb2.UtteranceSynthesisRequest(
        text=text,
        output_audio_spec=tts_pb2.AudioFormatOptions(
            container_audio=tts_pb2.ContainerAudio(
                container_audio_type=tts_pb2.ContainerAudio.WAV
            )
        ),
        loudness_normalization_type=tts_pb2.UtteranceSynthesisRequest.LUFS,
        hints=[tts_pb2.Hints(voice='filipp')]
    )

**Comment by tatlush** [comment]
Добрый день, @xvost ! Спасибо за интерес, проявленный к документации Yandex Cloud!
Вы правы, при работе с SpeechKit API v3 и авторизацией через IAM-токен требуется указывать folderID. Однако в этом примере используется сервисный аккаунт, об этом написано в шагах перед работой. Сервисный аккаунт может работать только в пределах доступного ему каталога, поэтому в примере не передается folderID. Подробнее о всех доступных вариантах авторизации можно почитать в документации: https://cloud.yandex.ru/docs/speechkit/concepts/auth

В дальнейшем мы планируем добавить другие примеры работы с API SpeechKit, но вы можете помочь нам с этим уже сейчас. Создайте PR с еще одним примером — с указанием голоса и авторизацией от имени пользователя (аккаунт на Яндексе или федеративный аккаунт), и мы начислим вам гран в рамках [контент-программы](https://cloud.yandex.ru/content-program). 

Ждем ваш PR в репозиторий!
