### ISSUE TITLE
Типы файлов для загрузки

### ISSUE THREAD

**Issue by exploadead** [yandex-cloud/docs#439]
В доке: "В настоящее время доступна загрузка только CSV-файлов."
Однако это не так. 
Файлы ТХТ загружаются без проблем. И даже файлы PHP тоже (не знаю правда зачем кому-то это делать)
Так что получается не только csv...

**Comment by antonydevanchi** [comment]
@exploadead а парсятся они всё равно как CSV.

@tatlush закрывайте, чего время тратить :)
