### ISSUE TITLE
Допущена ошибка в логике функции

### ISSUE THREAD

**Issue by sofieremi** [yandex-cloud/docs#448]
Пример данной функции не обрабатывает вариант запроса со стороны робота, нарушена логика 

# В этой части кода результат функции приравнивается к значению True в случае статуса запроса, не равного 200(успешного)

    if resp.status_code != 200: 
        print(f"Allow access due to an error: code={resp.status_code}; message={server_output}", file=sys.stderr)
        return True

# Здесь обработка успешного статуса запроса

    return json.loads(server_output)["status"] == "ok"

# А здесь происходит передача аргумента(токена) в функцию, и по описанной логике в любом варианте в результате ее выполнения будет вызван оператор    ->  print("Passed")

token = "<token>"
if check_captcha(token):
    print("Passed")
else:
    print("Robot")

Считаю необходимым изменить эту строку кода  "return True"   ->   на "return False" )

**Comment by tyamgin** [comment]
Добрый день!
В json-е ответа может быть status == "failed". Это означает, что пользователь прислал невалидный токен. Капчу следует считать непройденной. При этом `resp.status_code` будет равным 200.

`resp.status_code` и `json.loads(server_output)["status"]` - это не то же самое.
