### ISSUE TITLE
YA SpK + ASterisk

### ISSUE THREAD

**Issue by syberi** [yandex-cloud/docs#46]
Попробовал интегрировать синтезацию в астериск, никак не хочет принимать wav файлы(файлы читаемы в других проигрывателях) , конвертировал из lpcm sox > wav 8k -c 1 , в соответствии с требованиями кодека. При этом файлы из другого синтезатора в этом же проекте астериском проигрываются.

**Comment by MAnyKey** [comment]
Здравствуйте.
В вашем случае наилучшим решением будет обратиться в техподдержку.
