### ISSUE TITLE
Инструкция по подготовке API-ключа для использования Translate

### ISSUE THREAD

**Issue by thesyst** [yandex-cloud/docs#462]
В настоящий момент в документации есть лишь инструкция, рассказывающая как использовать Translate в своих bash/python скриптах. Но во многих случаях люди приходят чтобы просто узнать как получить API-ключ, который они будут вставлять в уже готовые решения. Сейчас для них нет быстрого способа разобраться в этом. Им приходиться читать про выдачу API-ключей и создание сервисных аккаунтов, прыгая по разным кускам документации.

Я предлагаю написать короткую инструкцию, которая будет решать задачу "Получение API-ключа для использования Yandex Translate".

В ней не будет ничего особенного, просто информация будет собрана в одном месте:
1. Описаны предварительные условия (наличие платежного аккаунта)
2. Создание сервисного аккаунта
3. Назначение роли ai.translate.user
4. Получение API-ключа

Думаю, что вариантов через CLI и Веб будет достаточно.

**Comment by tatlush** [comment]
@thesyst, здравствуйте!

Спасибо за ваше предложение! Вы совершенно правы, как правило, пользователи Yandex Translate меньше знакомы с остальными сервисами Yandex Cloud, и руководство, как подготовиться к работе им бы очень пригодилось.
Приносите вашу идею в виде PR, и мы начислим вам грант в рамках нашей [контент-программы](https://cloud.yandex.ru/content-program), получится полезная инструкция для наших пользователей. 
Предлагаю оформить его по шаблону сценария и разместить в разделе Пошаговые инструкции.

**Comment by tatlush** [comment]
По вашей просьбе мы добавили в документацию Yandex Translate и Yandex Vision руководства, как подготовить облако и сервисный аккаунт к работе.

https://cloud.yandex.ru/docs/translate/operations/sa-api-key
https://cloud.yandex.ru/docs/vision/operations/sa-api-key
