### ISSUE TITLE
Добавить примеры работы .NET с AWS SDK для Data Streams

### ISSUE THREAD

**Issue by RVShershnev** [yandex-cloud/docs#485]
Могу дополнить документацию по работе с [AWS SDK для Data Streams](https://cloud.yandex.ru/docs/data-streams/operations/aws-sdk/prepare) на основе [примера](https://github.com/yandex-cloud/yc-architect-solution-library/tree/main/yc-data-streams/YC.DataStreams.DataExchange).

**Comment by bazeltsev** [comment]
Спасибо за ваше предложение!
Приносите ваш пример в виде PR, и мы начислим вам грант в рамках нашей [контент-программы](https://cloud.yandex.ru/content-program), получится полезная инструкция для наших пользователей.
