### ISSUE TITLE
Не получается проверить работу тестового приложения

### ISSUE THREAD

**Issue by kuzyara** [yandex-cloud/docs#5]
![image](https://user-images.githubusercontent.com/2604430/50890621-7f1dea80-1435-11e9-8c08-17277d4baf03.png)

На шаге 3 выдает 502 Bad Gateway

И ещё, по-умолчанию пакет jq недоступен, после apt update поставилось.

**Comment by zamulla** [comment]
@kuzyara 
можно ссылку на страницу, которую вы читаете? Какое именно тестовое приложение не получается проверить?

**Comment by kuzyara** [comment]
https://cloud.yandex.ru/docs/solutions/testing/ci-for-snapshots#test-app

**Comment by zamulla** [comment]
Спасибо, посмотрим.

**Comment by SerjKanunnikov** [comment]
@kuzyara В конфигурации сервиса `/etc/systemd/system/test-app.service` нужно поправить в путях имя папки с виртуальным окружением: вместо `venv` должно быть `test-venv`. 

Конфигурация с правильными путями:

~~~
#/etc/systemd/system/test-app.service
[Unit]
Description=uWSGI instance to serve test API
After=network.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/srv/test-app
Environment="PATH=/srv/test-app/test-venv/bin"
ExecStart=/srv/test-app/test-venv/bin/uwsgi --ini test-app.ini

[Install]
WantedBy=multi-user.target
~~~

В сценарии тоже исправим и добавим про `apt update`. Спасибо!
