### ISSUE TITLE
Notifications on CLI releases

### ISSUE THREAD

**Issue by daskol** [yandex-cloud/docs#503]
Is there any abilities to get notification or some kind of mailing about new releases of `yc` tool?

**Comment by daskol** [comment]
@zamulla Any feedback?

**Comment by nikolaymatrosov** [comment]
You'll get a notification right in the YC CLI after command result, if CLI detects that the newer version is available.
```
There is a new yc version '0.102.0' available. Current version: '0.101.0'.
See release notes at https://cloud.yandex.ru/docs/cli/release-notes
You can install it by running the following command in your shell:
	$ yc components update
```

**Comment by daskol** [comment]
@nikolaymatrosov Sure. How to subscribe to new releases?

**Comment by nikolaymatrosov** [comment]
As the CLI is developed in the private repo, there is no native way to subscribe to new releases. But you can check https://storage.yandexcloud.net/yandexcloud-yc/release/stable periodically to find out if a new version is available as the CLI do.

**Comment by daskol** [comment]
@nikolaymatrosov Yes, this is exactly what I regularly do. I noticed that the changelog of `yc` is updated in accordance with each release. So, is there any way to create a release or a tag specific to release of `yc` in public repo? Is it possible to revive the old machinery which used ticket keys as tags two years ago.

BTW It would be great to add a flag to disable new release warning in CLI (like `--no-python-version-warning`  in `pip`) for better experience.

**Comment by iglunchadze** [comment]
Hi @daskol, and thank you for the suggestion!

In the docs, there are [CLI release notes](https://cloud.yandex.com/en/docs/cli/release-notes). This English version can sometimes fall slightly behind [the Russian one](https://cloud.yandex.ru/docs/cli/release-notes). 

Other channels of notification are out of scope of the docs and this repo. You can add you suggestion to our [features space](https://cloud.yandex.ru/features) (Russian). The Yandex Cloud teams keep an eye on that page and implement popular proposed features. Maybe yours will also be taken up :)
