### ISSUE TITLE
Incorrect helm repo for yc-ingress-controller

### ISSUE THREAD

**Issue by misty-fungus** [yandex-cloud/docs#522]
At alb [docs](https://cloud.yandex.com/en/docs/application-load-balancer/tools/k8s-ingress-controller/)
repository `oci://cr.yandex/yc/yc-alb-ingress-controller-chart` is used. However it does not work.

However marketplace [docs](https://cloud.yandex.com/en/marketplace/products/yc/alb-ingress-controller)
use correct repository `oci://cr.yandex/yc-marketplace/yandex-cloud/yc-alb-ingress/yc-alb-ingress-controller-chart`

Please note alb & marketplace version mismatch: 0.1.12 versus 0.1.13

**Comment by iglunchadze** [comment]
Hi @misty-fungus! Thank you for the heads-up! We are already aware of the issue and will fix it shortly.

**Comment by iglunchadze** [comment]
We've fixed the issue, at least partially:

* Step-by-step instructions both in [Application Load Balancer](https://cloud.yandex.com/en/docs/application-load-balancer/operations/k8s-ingress-controller-install) and [Managed Service for Kubernetes](https://cloud.yandex.com/en/docs/managed-kubernetes/operations/applications/alb-ingress-controller) docs refer to the correct URL.
* In the [overview article](https://cloud.yandex.com/en/docs/application-load-balancer/tools/k8s-ingress-controller/) mentioned in the initial comment, "embedded" instructions are replaced with a link.

We're working on a solution that will allow to synchronize Helm chart versions in the Marketplace and in the docs, but at least the instructions can now be followed.
