### ISSUE TITLE
Не хватает списка минимального набора ролей для создания managed kubernetes

### ISSUE THREAD

**Issue by eSerpentine** [yandex-cloud/docs#543]
По документации совершенно непонятно, какие должны быть роли у пользователя или сервисного аккаунта, который создает кубернетес кластер. 

Только после общения с саппортом, удалось выяснить что кроме k8s.editor, еще нужна роль iam.serviceAccounts.user, о которой в документации ни слова.

**Comment by daeremina** [comment]
Здравствуйте! Спасибо за комментарий, в ближайшее время добавим в документацию всю необходимую информацию о ролях.
