### ISSUE TITLE
Missed files: `deploy/create-func.sh` and `deploy/create-func-ver.sh` 

### ISSUE THREAD

**Issue by ildar-gilmanov** [yandex-cloud/docs#560]
The `deploy/create-func.sh` and `deploy/create-func-ver.sh` files are mentioned in the documentation: [Подключение к базе данных Yandex Managed Service for YDB из функции Cloud Functions на Node.js](https://cloud.yandex.ru/docs/functions/tutorials/connect-to-ydb-nodejs), but the repository [ydb-nodejs-sdk](https://github.com/ydb-platform/ydb-nodejs-sdk.git) does not contain the directory and the files.

The source documentation page: [connect-from-cf-nodejs.md](https://github.com/yandex-cloud/docs/blob/master/ru/_tutorials/connect-from-cf-nodejs.md)

**Comment by myusosnovskay** [comment]
Здравствуйте!

Была неправильная ссылка на репозиторий, поправили. Файлы находятся здесь: https://github.com/yandex-cloud/examples/tree/master/serverless/functions/YDB-connect-from-serverless-function.
