### ISSUE TITLE
Docker образ для Datasphere с требуемой версией tensorflow и cuda

### ISSUE THREAD

**Issue by ml-inr** [yandex-cloud/docs#564]
Добрый день!

Иногда при использовании Datasphere требуется не предустановленная версия tensorflow (2.6), а специальная, например, 2.12. Просто обновить TF с помощью pip недостаточно - нужно также поставить правильную версии графических библиотек (cuda). По этой причине необходимо собирать docker образ со всеми правильными библиотеками и активировать его в проекте. Существующее руководство и примеры не покрывают этот вопрос. Хуже того, пример с загрузкой драйверов cuda "устарел" в том смысле, что есть гораздо более простой способ поставить требуемую версию cuda - с помощью conda (см., например, https://www.tensorflow.org/install/pip). Ниже приведен пример как можно создать docker образ с требуемой предустановленной версией TF, совместимый с datasphere, использующий python 3.9.

```
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN useradd -ms /bin/bash --uid 1000 jupyter\
&& apt update\
&& apt install -y python3.9-dev python3.9-distutils curl wget\
&& ln -s /usr/bin/python3.9 /usr/local/bin/python3\
&& curl https://bootstrap.pypa.io/get-pip.py | python3\
&& wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.3.1-0-Linux-x86_64.sh -O ~/miniconda.sh

ENV CONDA_DIR=/opt/conda
ENV PATH=:$CONDA_DIR/bin:$CONDA_DIR/condabin:$PATH

RUN /bin/bash ~/miniconda.sh -b -f -p $CONDA_DIR

RUN ln -s $CONDA_DIR/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN conda install -c conda-forge cudatoolkit=11.8.0\
 && python -m pip install nvidia-cudnn-cu11==8.6.0.163 tensorflow==2.12.*

RUN touch tf_env_vars.sh\
 && echo 'CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' >> tf_env_vars.sh\
 && echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' >> tf_env_vars.sh\
 && /bin/bash -c 'source tf_env_vars.sh'

ENV LD_LIBRARY_PATH=:/opt/conda/lib/:/opt/conda/lib/python3.9/site-packages/nvidia/cudnn/lib
```

Последняя строка потенциально может быть разной для разных версий cudnn.  Более точно, она должна совпадать с тем, что записано для LD_LIBRARY_PATH в tf_env_vars.sh.

Пожалуйста, добавьте соответствующие инструкции в документацию - это потенциально сохранит много времени многим людям. Ещё лучше - предсоздайте образы с разными версиями TF, аналогично образам "Default Python 3.8", доступные всем.

Также, при общении со службой поддержи было выяснено, что для того, чтобы образ прошел проверки, проект datasphere должен быть подключен к NAT-шлюзу (https://cloud.yandex.ru/docs/vpc/operations/create-nat-gateway, https://cloud.yandex.ru/docs/datasphere/operations/projects/update).

**Comment by MaksimAliev** [comment]
А воз и ныне там :(
