### ISSUE TITLE
Информация о поддержке node_modules

### ISSUE THREAD

**Issue by Rukomoynikov** [yandex-cloud/docs#58]
Привет. Где найти информацию о том поддерживается ли node_modules. Насколько я понял - нет?

**Comment by iredun** [comment]
> Привет. Где найти информацию о том поддерживается ли node_modules. Насколько я понял - нет?

На сколько знаю, все зависимости и код нужно одним архивом загружать.

**Comment by MAnyKey** [comment]
Здравствуйте.
Можете уточнить контекст вашего вопроса? 
Пока мне кажется, что вопрос скорее про https://github.com/yandex-cloud/nodejs-sdk и лучше задать его там.
