### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by Antipascal** [yandex-cloud/docs#584]
Link with documentation for Terraform configuration of YC Lockbox is not working

[file](https://github.com/yandex-cloud/docs/blob/master/ru/_includes/lockbox/secret-create.md)
```
Более подробную информацию о параметрах ресурса yandex_lockbox_secret в Terraform, см. в [документации провайдера]({{ tf-provider-link }}/lockbox_secret).
```

**Comment by AlexJameson** [comment]
@Antipascal Hello. Thanks for your correction, it's absolutely valid. According to the rules of our content program, you can receive a grant for the Yandex Cloud usage. Please provide the ID of your billing account in Yandex Cloud.
