### ISSUE TITLE
Yandex captcha отсутствует параметр onTokenExpired

### ISSUE THREAD

**Issue by Christopher-md** [yandex-cloud/docs#593]
В документации к yandex-captcha для React приложения у вас в таблице указано, что есть такой параметр как `onTokenExpired` (https://cloud.yandex.com/en/docs/smartcaptcha/concepts/react), который мне бы пригодился в разработке при работе с валидацией. 

При разработке и установке данной библиотеке в своем проекте данный параметр я не нашел. Не могли бы вы помочь мне с этим. 

Если кто-то сталкивался с этим, то подскажите как вы решали данную проблему?

Библиотека: `@yandex/smart-captcha`
Версия пакета: `2.2.0`

**Comment by Nnigmat** [comment]
Также, данная функциональность прямо сейчас не работает. К сожалению, возник ряд сложностей при выкатке SmartCaptcha, из-за чего данная функциональность все еще отсутствует на проде. Но, обработчик данного ивента можно добавить уже сейчас без каких-либо проблем, и он заработает как только мы выложим новую версию SmartCaptcha
