### ISSUE TITLE
InvisibleSmartCaptcha. Не отрабатывает метод onTokenExpired

### ISSUE THREAD

**Issue by yomche** [yandex-cloud/docs#617]
При использовании компонента `InvisibleSmartCaptcha` не удаётся обработать следующий флоу: 
1. При успешной отработке метода `onSuccess` происходит запись токена через useState.
2. Если токен пользователя становится невалидным, то необходимо вызвать метод `onTokenExpired`, таким образом сбрасывая невалидный токен до пустой строки.
3. Если записанный токен был засчитан как невалидный и сброшен до пустой строки, то запускать повторное открытие капчи при каком - то триггере (при нажатии на кнопку).

Однако метод `onTokenExpired` не отрабатывает так, как ожидается во флоу выше. 

![image](https://github.com/yandex-cloud/docs/assets/31934798/71a42774-567c-408d-b891-d4e2b0add56d)

Подскажите, пожалуйста, что в данном случае сделано не так, как это можно исправить? Как обойти или решить данную проблему?  

`React JS`
Библиотека: `@yandex/smart-captcha`
Версия пакета: `^2.4.12`

**Comment by operator-nss** [comment]
Аналогичная проблема

**Comment by Nnigmat** [comment]
Привет! Починил. Стенд, на котором можно посмотреть - https://codesandbox.io/s/invisiblesmartcaptcha-react-test-ontokenexpired-2lj973

Обновлять пакет не нужно, потому что проблема была в нативном модуле SmartCaptcha.
