### ISSUE TITLE
Настройку aws-cli можно улучшить в связи с последними обновлениями

### ISSUE THREAD

**Issue by freehck** [yandex-cloud/docs#622]
Вот, ознакомьтесь: https://aws.amazon.com/blogs/developer/new-improved-flexibility-when-configuring-endpoint-urls-with-the-aws-sdks-and-tools/

Коротко, в версиях aws-cli 1.29.0+ и 2.13.0+ в .aws/credentials можно использовать параметр endpoint_url

Например так:
[default]
aws_access_key_id = <...>
aws_secret_access_key = <...>
endpoint_url = https://storage.yandexcloud.net

После такой настройки можно дёргать просто aws s3 ls

**Comment by vnkiryushkin** [comment]
@freehck Спасибо за предложение. Внесли в доку изменение, будет опубликовано 16.10.23 вот тут: https://cloud.yandex.ru/docs/storage/tools/aws-cli.

Напишите сюда, пожалуйста, [идентификатор платежного аккаунта](https://cloud.yandex.ru/docs/billing/concepts/billing-account#billing-account-id) в Yandex Cloud, чтобы мы могли начислить вам грант в рамках [контент-программы](https://cloud.yandex.ru/content-program).

**Comment by freehck** [comment]
@vnkiryushkin 
`dn2cc68ogre7nghaeooo`

**Comment by vnkiryushkin** [comment]
@freehck Грант выдан.
