### ISSUE TITLE
Для зон доступности не указаны географические локации

### ISSUE THREAD

**Issue by rutven** [yandex-cloud/docs#63]
В описании зон доступности не указаны географические локации этих зон - [geo-scope](https://github.com/yandex-cloud/docs/blob/master/ru/overview/concepts/geo-scope.md)

**Comment by userdeka** [comment]
Добрый день! Спасибо за интерес к облачной документации. Информация о географическом местоположении зон доступности описана в документе. Они расположены во Владимирской, Рязанской и Московской областях.

**Comment by rutven** [comment]
Имелось в виду, что непонятно соответствие названия зоны и географической локации.
