### ISSUE TITLE
C terraform 1.6.x для S3 бэкэнда нужен флаг skip_s3_checksum 

### ISSUE THREAD

**Issue by EnergoStalin** [yandex-cloud/docs#652]
S3 бэкэнд не работает после 1.6.x версии терраформа без дополнительного флага добавленного в [1.6.3](https://github.com/hashicorp/terraform/releases/tag/v1.6.3). Версии с 1.6.x до 1.6.2 вроде как сломаны тестил только 1.6.2. Пул [реквест](https://github.com/hashicorp/terraform/pull/34127) с флагом.

**Comment by vnkiryushkin** [comment]
@EnergoStalin здравствуйте, спасибо что подсветили. Проверили, все действительно так. Напишите сюда, пожалуйста, [идентификатор платежного аккаунта](https://cloud.yandex.ru/docs/billing/concepts/billing-account#billing-account-id) в Yandex Cloud, чтобы мы могли начислить вам грант в рамках [контент-программы](https://cloud.yandex.ru/content-program).

ПР с изменениями в документации смержен. Опубликуем на русском 16.11.23 вечером вот тут: https://cloud.yandex.ru/docs/tutorials/infrastructure-management/terraform-state-storage#set-up-backend.

**Comment by EnergoStalin** [comment]
Не ожидал такого но спасибо.

id: dn28ad8qq6o5d2sr2uu1
