### ISSUE TITLE
Систематическая ошибка при распознавании документов.

### ISSUE THREAD

**Issue by Sanifrey** [yandex-cloud/docs#653]
Приветствую!
Спасибо за хороший и доступный продукт.
Вот три постоянные ошибки распознавания паспорта РФ, которые были найдены за 2 месяца тестирования и использования:

1) При распознавании паспорта РФ: если в документе дата рождения 2001-2009, то всегда распознаёт будто год рождения: 1901-1909. Месяц и день распознает правильно, а вот год постоянно неправильно. Видимо модель по которой происходило обучение не содержало паспорта с такими годами (предположение).

Примеры ошибок с датой рождения в паспорте РФ:
В паспорте | распознано
2001 | 1901
2002 | 1902
2003 | 1903
2004 | 1904
2005 | 1905
2006 | 1906
2007 | 1907
2008 | 1908
2009 | 1909

2) При распознавании паспорта РФ: Если в документе серия паспорта 18**2**2, то распознавание определит как 18**1**2. Или же в паспорте серия: 22**2**3, то распознавание определит как 22**1**3. Ошибка каждый раз повторяется с третьей цифрой серии паспорта РФ, если там будет цифра **2**. Причина думаю аналогична той, которая была в предыдущей ошибке.

Примеры ошибок с серией паспорта РФ:
В паспорте | распознано
1822 | 1812
0322 | 0312
9222 | 9212

3) При распознавании паспорта РФ: Если в паспорте РФ дата выдачи документа 2021, то распознавание определит как 2011. Причина думаю та же что и в предыдущих двух.

Примеры ошибок с датой выдачи паспорта РФ:
В паспорте | распознано
2021 | 2011
2022 | 2012
2023 | 2013

Ошибки были обнаружены при работе со сканами документов. Сканы были качества 2480х3507. Изображения формата jpg.

**Comment by tatlush** [comment]
@Sanifrey Дамир, здравствуйте! Подскажите, я правильно поняла, что речь о сервисе Yandex Vision?

**Comment by Sanifrey** [comment]
> @Sanifrey Дамир, здравствуйте! Подскажите, я правильно поняла, что речь о сервисе Yandex Vision?

Да, абсолютно верно. Yandex Vision -> Распознавание документов -> text_detection_config:passport. 

Язык распознавания: Ru.

**Comment by diam80** [comment]
Подтверждаю. Эту ошибку уже больше двух месяцев не могут исправить. Когда уже?

**Comment by diam80** [comment]
> @Sanifrey Дамир, здравствуйте! Подскажите, я правильно поняла, что речь о сервисе Yandex Vision?

Подскажите, Яндекс скажет хоть что-нибудь? Инцидент подтвержден? В работе? Им кто-нибудь занимается?

**Comment by tatlush** [comment]
@Sanifrey Дамир, @diam80 Дмитрий, ваши замечания разработчикам передали. Проблема действительно существует, о ней знают, над решением работают, но точных сроков назвать не можем. 
Поскольку ошибка не связана с документацией, ваше issue закрою.

**Comment by eacentrru-hub** [comment]
Подтверждаю, ошибка в серии паспорта вместо 0323 распознает 0313, в дате выдачи вместо 05.12.2023 возвращает 05.12.2013, и судя по последнему сообщению от 25.12.2023 года ничего не исправлено ((((
