### ISSUE TITLE
Inaccurate information about runtime environments in functions

### ISSUE THREAD

**Issue by nikpivkin** [yandex-cloud/docs#655]
Docs: 
- https://cloud.yandex.com/en/docs/functions/concepts/runtime/
- https://cloud.yandex.com/en/docs/functions/lang/golang/
- and other language-specific pages

I used the following command to get the runtime environments, but the list does not match the documentation: `yc serverless function runtime list`

Which runtimes are missed in the documentation?
- go121
- node18
- php82
- py312
- java21
- dotnet8
- bash2204
- r43

There are also some runtime present that CLI did not output:
- dotnetcore31
- r402
- r4

Also, the documentation specifies runtime `dotnetcore6`, but cli outputs `dotnet6`

**Comment by myusosnovskay** [comment]
Updated documentation: https://cloud.yandex.com/en/docs/functions/concepts/runtime/.
