### ISSUE TITLE
Некорректные параметры в документации "Управление жизненными циклами объектов в бакете"

### ISSUE THREAD

**Issue by nkt1222** [yandex-cloud/docs#693]
https://cloud.yandex.ru/ru/docs/storage/operations/buckets/lifecycles#cli_1
В документации указаны возможные параметры:
`noncurrent_version_transition` и `noncurrent_version_expiration`
![image](https://github.com/yandex-cloud/docs/assets/118337048/0c9a3194-64b6-41c8-9f88-9dd533149626)
В чем собственно проблема: при попытке загрузить жизненный цикл из файла:
[noncurrent_transition_from_doc.json](https://github.com/yandex-cloud/docs/files/14233092/noncurrent_transition_from_doc.json)

```
{
  "lifecycleRules": [
    {
      "enabled": true,
      "noncurrent_version_transition": {
        "days": 10,
        "storage_class": "COLD"
      }
    }
  ]
}
```
Выходит ошибка `ERROR: proto: (line 5:7): unknown field "noncurrent_version_transition"`
![image](https://github.com/yandex-cloud/docs/assets/118337048/52971a85-4d6d-44c3-acb7-5db3d16f673f)

При этом отрабатывает следующий код:
[noncurrent_transition.json](https://github.com/yandex-cloud/docs/files/14233144/noncurrent_transition.json)

```
{
  "lifecycleRules": [
    {
      "enabled": true,
      "noncurrent_transitions":
        [
          {
            "noncurrent_days": 10,
            "storage_class": "COLD"
          }
        ]
    }
  ]
}
```
![image](https://github.com/yandex-cloud/docs/assets/118337048/3d908a2d-0621-4ed8-b539-00f632996fc4)

То же самое с `noncurrent_version_expiration`. По документации следующий код должен работать
[noncurrent_expiration_from_doc.json](https://github.com/yandex-cloud/docs/files/14233159/noncurrent_expiration_from_doc.json)
```
{
  "lifecycleRules": [
    {
      "enabled": true,
      "noncurrent_version_expiration": {
        "days": 10
      }
    }
  ]
}
```
но он возвращает
`ERROR: proto: (line 5:7): unknown field "noncurrent_version_expiration"`
![image](https://github.com/yandex-cloud/docs/assets/118337048/04af3810-6f38-4608-90d7-58641c6555e6)
При этом работает:
[noncurrent_expiration.json](https://github.com/yandex-cloud/docs/files/14233170/noncurrent_expiration.json)

```
{
  "lifecycleRules": [
    {
      "enabled": true,
      "noncurrent_expiration": {
        "noncurrent_days": 10
      }
    }
  ]
}{
  "lifecycleRules": [
    {
      "enabled": true,
      "noncurrent_expiration": {
        "noncurrent_days": 10
      }
    }
  ]
}
```

**Comment by vnkiryushkin** [comment]
@nkt1222, здравствуйте. Проверили, действительно, вы правы.
ПР с правками смержен через внутренний процесс. Будет опубликовано 20.02.24 вечером в РУ-версии тут:
https://cloud.yandex.ru/ru/docs/storage/operations/buckets/lifecycles. EN чуть позднее.

Напишите, пожалуйста, сюда [идентификатор платежного аккаунта](https://cloud.yandex.ru/docs/billing/concepts/billing-account#billing-account-id) в Yandex Cloud, чтобы мы могли начислить вам грант в рамках [контент-программы](https://cloud.yandex.ru/content-program).
