### ISSUE TITLE
Нет пояснения к звёздочке в описании физической сети

### ISSUE THREAD

**Issue by tifv** [yandex-cloud/docs#710]
В разделе
https://github.com/yandex-cloud/docs/blob/master/en/_includes/overview/network.md#physical-network-in--yandex-cloud--underlay
на схеме физической сети элемент «ru-central1-d» обведен штрихом и подписан звёздочкой, но что это означает, из текста неясно. (В русской версии аналогично.)

**Comment by tatlush** [comment]
@tifv, здравствуйте!
Звездочка и пунктир у зоны d означают, что зона еще только планируется или не до конца запущена в эксплуатацию. 
Сейчас зоны c и d активно меняются, поэтому иллюстрации не всегда могут точно отражать текущий статус. Мы обязательно обновим все описания и схемы.

Спасибо, что обратили на это внимание!

**Comment by tatlush** [comment]
Мы обновили схемы в описании сети: https://yandex.cloud/ru/docs/overview/concepts/network
