### ISSUE TITLE
SDK для .NET

### ISSUE THREAD

**Issue by Mblkolo** [yandex-cloud/docs#72]
В документации постоянно встречается фраза

```
Примечание

Если вы используете SDK для .NET, обращайтесь к хосту s3.yandexcloud.net.
```

Но в [списке инструментов](https://cloud.yandex.ru/docs/storage/tools/), никакого SDK для .NET нет. 
О каком SDK идёт речь? Может добавить ссылку в документацию?

**Comment by alexey-formalmethods** [comment]
Насколько я понимаю, тут имеется в виду S3 SDK (https://aws.amazon.com/ru/sdk-for-net/). Туда можно любой хост написать, необязательно амазон, можно и s3.yandexcloud.net.

**Comment by iglunchadze** [comment]
Мы добавили в документацию статью об [SDK для .NET](https://cloud.yandex.ru/docs/storage/tools/aws-sdk-net). Забыли только поставить ссылку на неё в списке инструментов — скоро тоже добавим.
