### ISSUE TITLE
Неправильно указаны поля запроса в примере для REST v3

### ISSUE THREAD

**Issue by LeonKilgoreTrout** [yandex-cloud/docs#731]
В примере документации для ссылки https://cloud.yandex.com/en-ru/docs/speechkit/tts/api/tts-v3-rest
указан такой запрос
{"text":"Привет", "hints": [{"voice": "marina", "role": "friendly"}]}

Но судя по всему  параметр "voice" передается иначе. 
Т. к. подставляется дефолтный "alena" и возвращается такой ответ:
"message":"Unknown role 'friendly' for 'alena' voice

**Comment by tatlush** [comment]
@LeonKilgoreTrout, привет!
Мы уже исправили эту ошибку и в русской, и в английской документации. Правильный формат такой:

```
{"text": "Привет! Я Яндекс Спичк+ит. Я могу превратить любой текст в речь. Теперь и в+ы - можете!", "hints": [{"voice": "marina"}, {"role": "friendly"}]}
```

Спасибо за бдительность! :)

**Comment by LeonKilgoreTrout** [comment]
Не исправили, дело не в  поле "text", если подставить Ваш запрос, то вернёт тоже самое:
"message":"Unknown role 'friendly' for 'alena' voice ...
