### ISSUE TITLE
Clarify the user-data documentation

### ISSUE THREAD

**Issue by mipo256** [yandex-cloud/docs#744]
AWS EC2 supports user-data scripts to specify the initialization script to be used by VM on launch.
[This page](https://yandex.cloud/en/docs/compute/concepts/vm-metadata#tf_1) contains the example of using "VM metadata". In particular, it specifies the usage of _cloud-init.yaml_ config file. 

I suppose (and it is only my guess based on the provided content on the page), that this is supposed be a [cloud-init format file](https://cloudinit.readthedocs.io/en/latest/tutorial/lxd.html). But there is no any kind of information about what this file is, what is supported and what is not. 

Can you please improve documentation about "VM metadata"? It is highly unclear to understand how the start-up script can be used for VM.

**Comment by vnkiryushkin** [comment]
@mipo256 hello.
Thank you for your interest in Yandex Cloud documentation. We definitely need an instruction on how to use instance metadata to send an initial script. 

We are preparing this instruction and it will be available in Russian after the next documentation release on July 24, 2021 here: https://yandex.cloud/ru/docs/compute/operations/vm-create/create-with-cloud-init-scripts.

During the next week, it will also be available in English.
