### ISSUE TITLE
Инструкция по конфигурации OS Login для Ansible

### ISSUE THREAD

**Issue by leitosama** [yandex-cloud/docs#748]
Добрый день!

Хочу написать пошаговую инструкцию на основе своего исследования возможностей YC + OS Login для работы с Ansible.

Я задался вопросом создания сервисной учетной записи для ansible на ВМ с включенной опцией OS Login и хочется поделиться результатами с сообществом. Что будет описано:

- Как создать сервисную учетную запись в каталог
- Как добавить ей права для OS Login
- Как создать и добавить ключ для входа (cli only)
- Как подключаться и как использовать ansible

**Comment by AlexJameson** [comment]
@leitosama Здравствуйте! Такое руководство было бы очень полезно. Я бы предложил разместить его в двух местах - https://yandex.cloud/ru/docs/organization/ и в разделе «Безопасность» здесь https://yandex.cloud/ru/docs/tutorials/

Я вернусь к вам чуть позже с дополнительными деталями, которые могут быть полезны для такого руководства.

**Comment by leitosama** [comment]
@AlexJameson Привет!
Я форкнул репозиторий и написал основной текст, который должен быть в руководстве по моему мнению ([leitosama/yc-docs](https://github.com/leitosama/yc-docs/blob/master/ru/_tutorials/security/ansible-oslogin.md)).
У меня есть пару вопросов:
* Как происходит наше взаимодействие дальше? Будто бы надо прислать PR, но учитывая структуру репозитория для меня неочевидна граница необходимого вклада от меня
* Будет ли какое-то рецензирование статьи?

**Comment by AlexJameson** [comment]
> @AlexJameson Привет! Я форкнул репозиторий и написал основной текст, который должен быть в руководстве по моему мнению ([leitosama/yc-docs](https://github.com/leitosama/yc-docs/blob/master/ru/_tutorials/security/ansible-oslogin.md)). У меня есть пару вопросов:
> 
> * Как происходит наше взаимодействие дальше? Будто бы надо прислать PR, но учитывая структуру репозитория для меня неочевидна граница необходимого вклада от меня
> * Будет ли какое-то рецензирование статьи?

Приветствую. 
1. Да, нужно будет прислать пулл-реквест. В принципе, помимо изменений в процессе вычитки, вам сделать две вещи:
переместить свое руководство сюда https://github.com/leitosama/yc-docs/tree/master/ru/security/tutorials
добавить ссылку на него здесь https://github.com/leitosama/yc-docs/blob/master/ru/security/toc.yaml#L76
2. Да, рецензирование будет, я займусь им сразу, когда появится ПР. Сегодня я начну тестирование сценария. 

Вы можете пока что ознакомиться с правилами нашей контент-программы https://yandex.cloud/ru/content-program

**Comment by leitosama** [comment]
Добрый день!

Внес то что попросили + поправил мелкие ошибки. PR #775
