### ISSUE TITLE
Невалидная ссылка на yandexcloud-yc

### ISSUE THREAD

**Issue by antonsergeyev** [yandex-cloud/docs#756]
По адресу https://yandex.cloud/ru-kz/docs/cli/quickstart#macos_1 указана ссылка на bash скрипт для установки yc. По ней возвращается 404:
https://storage.yandexcloud.kz/yandexcloud-yc/install.sh

```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
<Resource>/yandexcloud-yc/install.sh</Resource>
<RequestId>428ab3c60c147e5a</RequestId>
</Error>
```

**Comment by vnkiryushkin** [comment]
@antonsergeyev Здравствуйте. Спасибо, что подсветили.

Используйте, пожалуйста, следующую команду:

```bash
curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
```

Для региона Казахстан используется тот же установочный скрипт, что и для региона Россия. Разница в настройке профиля: https://yandex.cloud/ru-kz/docs/cli/quickstart#initialize.

Доку KZ поправим в ближайшее время.

**Comment by vnkiryushkin** [comment]
@antonsergeyev доку поправили, Issue закрываю, спасибо.

https://yandex.cloud/ru-kz/docs/cli/quickstart
