### ISSUE TITLE
Ошибка при установке библиотеки speechKit

### ISSUE THREAD

**Issue by sorokin-as** [yandex-cloud/docs#757]
Делаю по инструкции у меня нет ни каких GRPC пакетов но либа отказывается ставиться! 
Уже 3 часа пытаюсь запустить быстрый старт)

![image](https://github.com/yandex-cloud/docs/assets/17888766/ba05e521-1671-4fc5-a80f-330393889d48)

**Comment by sorokin-as** [comment]
сделал все что тут написано https://yandex.cloud/ru/docs/speechkit/sdk/python/version-conflict

сделал вообще чистое окружение новое, плевать все равно ГРПС пакеты ставит. Зачем выкладитьвать такие либы?)

**Comment by tatlush** [comment]
@sorokin-as Андрей, здравствуйте!
gRPC пакеты и должны ставиться, без них SpeechKit не будет работать. 
какая ошибка возникает при установке Python SDK?

**Comment by sorokin-as** [comment]
> @sorokin-as Андрей, здравствуйте! gRPC пакеты и должны ставиться, без них SpeechKit не будет работать. какая ошибка возникает при установке Python SDK?

либа пытается установиться потом говорит что у нее ошибка и сама себя откатывает

**Comment by sorokin-as** [comment]
Мне с библиотекой через gRPC взаимодействовать? по REST API нет варианта?

**Comment by tatlush** [comment]
> либа пытается установиться потом говорит что у нее ошибка и сама себя откатывает

Попробуйте установить библиотеку в виртуальном окружении Python. 
Если не получится, создайте обращение в техническую поддержку Yandex Cloud. 

Python SDK предоставляет REST-интерфейс, но для ее работы необходим пакет grpc-tools. то, что при установке yandex-speechkit ставится и  grpc-tools, нормально и ожидаемо.

Также SpeechKit API v3 поддерживает REST для TTS и без использования библиотеки, а STT появится в ближайшем будущем.

**Comment by ZhakovArtyom** [comment]
Та же проблема, установка выходит с ошибкой и на ubuntu и в powershell

**Comment by tatlush** [comment]
> Та же проблема, установка выходит с ошибкой и на ubuntu и в powershell
@ZhakovArtyom, тот же совет, виртуальное окружение, если не поможет, пишите в поддержку. Тут мы вам, увы, помочь не сможем

**Comment by ZhakovArtyom** [comment]
Спасибо за ответ, у меня получилось установить на python 3.10 (3.11-3.12 выходили ошибки), но на этом ошибки не закончились.
при запуске будет, даже при установленной  ffmpeg 
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work

**Comment by tatlush** [comment]
@ZhakovArtyom  Виртуальное окружение создает "чистую" независимую среду. Скорее всего вы не установили в него ffmpeg.
