### ISSUE TITLE
Speech KIT: You have to specify folder ID for user account

### ISSUE THREAD

**Issue by theStrangeAdventurer** [yandex-cloud/docs#758]
Привет! Я пытаюсь использовать yandex speech kit и у меня проблема конкретно с синтезом речи (https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize), проблем с speech to text или text completion не возникло.

Я пытаюсь выполнять запросы из nodejs используя нативный fetch. folderId точно передается, я пытался его передать как в загловке x-folder-id, так и в теле запроса. Без разницы - получаю эту ошибку

`'{"error_code":"UNAUTHORIZED","error_message":"rpc error: code = Unauthenticated desc = You have to specify folder ID for user account"}'`

Вот что я пытался сделать 

Вариант 1

```javascript

const params = {
        text,
        lang,
        voice,
        emotion,
        format: 'mp3',
        folderId: process.env.FOLDER_ID,
    };

    var formBody = [];
    for (var property in params) {
        var encodedKey = encodeURIComponent(property);
        var encodedValue = encodeURIComponent(params[property]);
        formBody.push(encodedKey + "=" + encodedValue);
    }
    formBody = formBody.join("&");

    const headers = {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'
    };

    const response = await fetch('https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize', {
        method: 'POST',
        headers,
        data: formBody,
    });
```

Вариант 2

```javascript
const formData = new FormData();
    // https://cloud.yandex.com/en/docs/speechkit/tts/voices
    
    let voice = 'ermil';
    let emotion = 'good';

    formData.append('emotion', emotion);
    formData.append('text', text);
    formData.append('lang', lang);
    formData.append('voice', voice);
    formData.append('format', 'mp3');
    formData.append('folderId', process.env.FOLDER_ID);
   
    const headers = {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/x-www-form-urlencoded'
    };

    const response = await fetch('https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize', {
        method: 'POST',
        headers,
        data: formData,
    });
```
Не могли бы вы добавить в доку вариант отправки запроса из ноды, спасибо

P.S. онлайн конверторы из curl -> fetch тоже не помогли с решением этой проблемы

**Comment by theStrangeAdventurer** [comment]
Вариант, который сработал, может кому-то будет полезно, через нативный fetch так и не вышло, но с axios сработало

```javascript
import FormData from 'form-data';
import axios from 'axios';


export const speechSynthesis = async (text, token, lang = 'ru-RU') => {
    const formData = new FormData();
    // https://cloud.yandex.com/en/docs/speechkit/tts/voices
    
    let voice = 'ermil';
    let emotion = 'good';

    formData.append('emotion', emotion);
    formData.append('text', text);
    formData.append('lang', lang);
    formData.append('voice', voice);
    formData.append('format', 'mp3');
    formData.append('folderId', process.env.FOLDER_ID);
   
    const headers = {
        Authorization: `Bearer ${token}`,
        ...formData.getHeaders(),
    };

    const response = await axios.post('https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize', formData, {
        headers,
        responseType: 'arraybuffer'
    });

    return response.data; 
}
```

**Comment by tatlush** [comment]
@theStrangeAdventurer Алексей, здравствуйте!

Спасибо за ваш опыт! Пожалуйста, сделайте PR с новым руководством для SpeechKit, и мы дадим Вам грант в рамках [контент-программы](https://yandex.cloud/ru/content-program).
За основу можно взять существующее руководство (например, https://yandex.cloud/ru/docs/speechkit/tts/api/tts-ogg) и оформить его для nodejs.

**Comment by theStrangeAdventurer** [comment]
@tatlush Привет! Открыл Пулл реквест с примерами запросов из NodeJS

**Comment by tatlush** [comment]
@theStrangeAdventurer, отлично, большое спасибо, забираю!
Еще мне нужен идентификатор вашего платёжного аккаунта, чтобы начислить грант.

**Comment by theStrangeAdventurer** [comment]
> @theStrangeAdventurer, отлично, большое спасибо, забираю!
> Еще мне нужен идентификатор вашего платёжного аккаунта, чтобы начислить грант. 

Без проблем, как это лучше сделать? Скинуть на почту или прямо сюда (достаточно ли это безопасно?)

**Comment by tatlush** [comment]
> Без проблем, как это лучше сделать? Скинуть на почту или прямо сюда (достаточно ли это безопасно?)

можно прямо сюда, по этому id никто ничего не сможет сделать, никакие действия платежному аккаунту не доступны, поэтому никак вас не скромпроментирует :)

**Comment by tatlush** [comment]
Спасибо! В ближайшее время грант будет начислен.
