### ISSUE TITLE
Отсутствует информация о подключении к Read-only реплике кластера

### ISSUE THREAD

**Issue by alex-vlasov-l1** [yandex-cloud/docs#77]
В разделах документации https://cloud.yandex.ru/docs/managed-postgresql/operations/connect#with-a-driver-that-supports-only-one-host 
и
https://cloud.yandex.ru/docs/managed-postgresql/operations/connect#with-a-driver-that-supports-only-one-host
Описан процесс подключения к мастеру через CNAME который всегда указывает на него "c-<идентификатор кластера>.rw.mdb.yandexcloud.net"
Однако в сервисах mysql и postgre присутсвует возможность также и подключиться к read-only реплике под общим CNAME вида c-<идентификатор кластера>.ro.mdb.yandexcloud.net. (ro вместо rw) - но в документации это не отражено, и клиенты пытаются собирать собственные кривые схемы обращения к реплике вместо того, чтобы использовать готовое решение.

Нужно добавить раздел рассказывающий, о том что на read-only реплику указывает запись вида c-<идентификатор кластера>.ro.mdb.yandexcloud.net

**Comment by a-chegodaev** [comment]
Добавили недостающую информацию:

* Managed PostgreSQL: https://cloud.yandex.ru/docs/managed-postgresql/operations/connect#fqdn-replica
* Managed MySQL: https://cloud.yandex.ru/docs/managed-mysql/operations/connect#fqdn-replica

Спасибо, что делаете документацию Yandex.Cloud лучше!
