### ISSUE TITLE
Когда свой cli  доделаете ?

### ISSUE THREAD

**Issue by ppskmg** [yandex-cloud/docs#803]
Каждый раз для работы с bucket приходится s3cmd накатывать. 
Вместо yc .. погнали. 
А yc -h вообще для галочки.
Через доку на сайте тоже каждый раз искать приходится.

**Comment by vnkiryushkin** [comment]
@ppskmg, здравствуйте. Спасибо за неравнодушное отношение к сервисам Yandex Cloud. Не совсем к документации ваше ишью, но тем не менее. Вы можете предложить свои идеи по улучшению сервисов тут: https://yandex.cloud/ru/features.

Мы начали реализовывать возможности aws s3 api в нашем cli. Пока тестово доступны следующие команды: `get-object`, `put-object`, `delete-object`, `copy-object`, `head-object`, `delete-objects`. Функциональность будет расширяться. Подробнее см. на странице [Релизы YC CLI](https://yandex.cloud/ru/docs/cli/release-notes#version0.134.0).

По поводу `--help`: мы совершенствуем справку как в самой утилите, так и справочник на сайте, следите за обновлениями.
