### ISSUE TITLE
ClickHouse: не хватает информации как настроить интеграцию с Kafka

### ISSUE THREAD

**Issue by gtors** [yandex-cloud/docs#93]
https://cloud.yandex.ru/docs/managed-clickhouse/operations/

Нет информации как связать Managed Service for ClickHouse  с Managed Service for Kafka.

Я в доп. настройках к кластеру ClickHouse указал креды для доступа к Kafka (9092 порт + SCRAM-SHA-512 + SASL_PLAINTEXT),  [согласно документации](https://clickhouse.tech/docs/ru/engines/table-engines/integrations/kafka/) создал queue, table и material view . Но сообщения как не приходили, так и не приходят.

**Comment by a-chegodaev** [comment]
Добрый день!
Недавно мы добавили в документацию Managed Service for ClickHouse практическое руководство [Получение данных из Managed Service for Apache Kafka®](https://cloud.yandex.ru/docs/managed-clickhouse/tutorials/fetch-data-from-mkf). Решает ли оно вашу проблему?

**Comment by gtors** [comment]
Добрых сумерек. Да, теперь все отлично. Благодарю!
